<?php require 'templates/layout/header.phtml';
$sneakers = $sneaker;
?>
<div class="BackgroundDetails">
    <?php if (!empty($sneaker->imagen)): ?>
        <img class="imgDetails" src="<?= htmlspecialchars($sneaker->imagen) ?>" alt="Imagen de la propiedad">
    <?php endif; ?>
</div>
<div class="details">
    <h5><?php echo htmlspecialchars($sneakers->nombre); ?></h5>
    <p><?php echo htmlspecialchars($sneakers->marca); ?></p>
    <p>$<?php echo htmlspecialchars($sneakers->precio); ?></p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, sequi. Quae sapiente maxime quaerat ex iure? Dolorum, sit quo sed dicta quia eum molestiae ex? Nobis asperiores atque quas eius.</p>
    <!-- <?php if ($this->user && $this->user->user <> NULL): ?>
                    <a href="agregar-modificarPropiedad">Seguir modificando propiedades</a>
                <?php endif; ?> -->
</div>

<?php require 'templates/layout/footer.phtml'; ?>