<?php require 'templates/layout/header.phtml';
$sneakers = $sneaker;
?>
<div class="BackgroundDetails">
    <?php if (!empty($sneaker->imagen)): ?>
        <img class="imgDetails" src="<?= htmlspecialchars($sneaker->imagen) ?>" alt="Imagen de la propiedad">
    <?php endif; ?>
</div>
<div class="details">
    <h5><?php echo htmlspecialchars($sneakers->nombre); ?></h5>
    <p><?php echo htmlspecialchars($sneakers->marca); ?></p>
    <p>$<?php echo htmlspecialchars($sneakers->precio); ?></p>

    <div>Talles disponibles:</div>
    <section class="talles">
        <?php for ($i = 0; $i < 10; $i++): ?>
            <button class="talle"><?php echo $i + 35; ?></button>
        <?php endfor; ?>
    </section>

    <button class="compra">Comprar</button>
    <!-- <?php if ($this->user && $this->user->user <> NULL): ?>
                    <a href="agregar-modificarPropiedad">Seguir modificando propiedades</a>
                <?php endif; ?> -->
</div>

<?php require 'templates/layout/footer.phtml'; ?>