<?php require 'templates/layout/header.phtml';
$error = $error ?>
<div class="video-background">
    <iframe src="https://www.youtube.com/embed/_1yduVlEx1Q?autoplay=1&mute=1&loop=1&playlist=_1yduVlEx1Q&controls=0&showinfo=0&modestbranding=1" frameborder="0"
        allow="autoplay; fullscreen"
        allowfullscreen>
    </iframe>
</div>
<div class="content">
    <form class='formLogin' method='post' action='login'>
        <h3>Logueate y unete a la familia</h3>
        <div class="sectionlogin"><label for='usuario'>Usuario</label>
            <input type='usuario' id='usuario' name='usuario' required>
            <label for='password'>Password</label>
            <input type='password' id='password' name='password' required>
        </div>
        <button type='submit'>Login</button>
    </form>
</div>
<?php require 'templates/layout/footer.phtml' ?>