<!DOCTYPE html>
<html lang="en">

<!-- head -->

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="./img/logoZapa.png" type="image/png">
    <link rel="stylesheet" href="./css/style.css">
    <title>SneakerHouse</title>
</head>

<body>
    <header class="header">
        <div class="logos">
            <div class="marcas">
                <a href="nike"><img src="./img/Nike-logo.png" alt="logoNike" class="logoMarca"></a>
                <a href="puma"><img src="./img/Puma-logo.png" alt="logoPuma" class="logoMarca"> </a>
            </div>
            <a href="home"><img src="./img/SneakerHouse.png" alt="SnakerHouse" class="logo"></a>
            <div class="marcas">
                <a href="adidas"><img src="./img/Adidas-logo.png" alt="logoAdidas" class="logoMarca"> </a>
                <a href="vans"><img src="./img/vans-logo.png" alt="vanslogo" class="logoMarca"> </a>
            </div>
        </div>
        <div class="nav">
            <a href="home">Inicio</a>
                <a href="marcas">Marcas</a>
            <a href="showLogin">Iniciar Sesión</a>
            <a href="carrito">
                <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#ffffff">
                    <path d="M280-80q-33 0-56.5-23.5T200-160q0-33 23.5-56.5T280-240q33 0 56.5 23.5T360-160q0 33-23.5 56.5T280-80Zm400 0q-33 0-56.5-23.5T600-160q0-33 23.5-56.5T680-240q33 0 56.5 23.5T760-160q0 33-23.5 56.5T680-80ZM246-720l96 200h280l110-200H246Zm-38-80h590q23 0 35 20.5t1 41.5L692-482q-11 20-29.5 31T622-440H324l-44 80h480v80H280q-45 0-68-39.5t-2-78.5l54-98-144-304H40v-80h130l38 80Zm134 280h280-280Z" />
                </svg>
            </a>
        </div>
    </header>

    <main class="container">