<!DOCTYPE html>
<html lang="en">

<!-- head -->

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="./img/logoZapa.png" type="image/png">
    <link rel="stylesheet" href="./css/style.css">
    <title>SneakerHouse</title>
</head>

<body>
    <header class="header">
        <div class="logos">
            <img src="./img/Nike-logo.png" alt="logoNike" class="logoMarca">
            <img src="./img/Puma-logo.png" alt="logoPuma" class="logoMarca">

            <img src="./img/SneakerHouse.png" alt="SnakerHouse" class="logo">

            <img src="./img/Adidas-logo.png" alt="logoAdidas" class="logoMarca">
            <img src="./img/vans-logo.png" alt="vanslogo" class="logoMarca">

        </div>
        <div class="nav">
            <a href="home">Inicio</a>
            <a href="">Marcas</a>
            <a href="showLogin">Iniciar Sesión</a>
        </div>
    </header>

    <main class="container">